version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

    networks:
      - my_network

  server:
    build:
      dockerfile: dockerfile
      context: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - my_network
    volumes:
      - ./:/JBTC
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  my_network: